# -*- coding: utf-8 -*-
"""Classify Handwritten Digits with Tensorflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dSlzW8CEHr0XXHS3aSXAIyVRn3WMNrS4
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train = x_train.reshape(-1, 784).astype("float32") / 255.0
x_test = x_test.reshape(-1, 784).astype("float32") / 255.0

y_train_cat = to_categorical(y_train, 10)
y_test_cat = to_categorical(y_test, 10)

max_examples = 10000
x_train = x_train[:max_examples]
y_train_cat = y_train_cat[:max_examples]
y_train = y_train[:max_examples]

def display(i):
    plt.title(f"Label: {y_test[i]}")
    plt.imshow(x_test[i].reshape(28, 28), cmap="gray")

model = Sequential([
    Dense(10, activation="softmax", input_shape=(784,))  # Linear classifier
])

model.compile(optimizer="sgd",
              loss="categorical_crossentropy",
              metrics=["accuracy"])

model.fit(x_train, y_train_cat, batch_size=100, epochs=5)

loss, accuracy = model.evaluate(x_test, y_test_cat)
print("Accuracy:", accuracy)

prediction = np.argmax(model.predict(x_test[0].reshape(1, 784)))
print(f"Prediction: {prediction},  Label: {y_test[0]}")

if prediction == y_test[0]:
    display(0)